package com.fnbory.myblog.entities;

import java.io.Serializable;
import java.util.Date;

public class Article implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.user_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_newstime
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Date articleNewstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_status
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer articleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_summary
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String articleSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_thumbnail
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String articleThumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_title
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_type
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer articleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_post
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String articlePost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_comment_status
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer articleCommentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_lasttime
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Date articleLasttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String articleUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_views
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Long articleViews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_content
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String articleContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_content_md
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String articleContentMd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.user_id
     *
     * @return the value of article.user_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.user_id
     *
     * @param userId the value for article.user_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_newstime
     *
     * @return the value of article.article_newstime
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Date getArticleNewstime() {
        return articleNewstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_newstime
     *
     * @param articleNewstime the value for article.article_newstime
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleNewstime(Date articleNewstime) {
        this.articleNewstime = articleNewstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_status
     *
     * @return the value of article.article_status
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getArticleStatus() {
        return articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_status
     *
     * @param articleStatus the value for article.article_status
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleStatus(Integer articleStatus) {
        this.articleStatus = articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_summary
     *
     * @return the value of article.article_summary
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getArticleSummary() {
        return articleSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_summary
     *
     * @param articleSummary the value for article.article_summary
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleSummary(String articleSummary) {
        this.articleSummary = articleSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_thumbnail
     *
     * @return the value of article.article_thumbnail
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getArticleThumbnail() {
        return articleThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_thumbnail
     *
     * @param articleThumbnail the value for article.article_thumbnail
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleThumbnail(String articleThumbnail) {
        this.articleThumbnail = articleThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_title
     *
     * @return the value of article.article_title
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_title
     *
     * @param articleTitle the value for article.article_title
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_type
     *
     * @return the value of article.article_type
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getArticleType() {
        return articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_type
     *
     * @param articleType the value for article.article_type
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleType(Integer articleType) {
        this.articleType = articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_post
     *
     * @return the value of article.article_post
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getArticlePost() {
        return articlePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_post
     *
     * @param articlePost the value for article.article_post
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticlePost(String articlePost) {
        this.articlePost = articlePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_comment_status
     *
     * @return the value of article.article_comment_status
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getArticleCommentStatus() {
        return articleCommentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_comment_status
     *
     * @param articleCommentStatus the value for article.article_comment_status
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleCommentStatus(Integer articleCommentStatus) {
        this.articleCommentStatus = articleCommentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_lasttime
     *
     * @return the value of article.article_lasttime
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Date getArticleLasttime() {
        return articleLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_lasttime
     *
     * @param articleLasttime the value for article.article_lasttime
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleLasttime(Date articleLasttime) {
        this.articleLasttime = articleLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_url
     *
     * @return the value of article.article_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getArticleUrl() {
        return articleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_url
     *
     * @param articleUrl the value for article.article_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleUrl(String articleUrl) {
        this.articleUrl = articleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_views
     *
     * @return the value of article.article_views
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Long getArticleViews() {
        return articleViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_views
     *
     * @param articleViews the value for article.article_views
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleViews(Long articleViews) {
        this.articleViews = articleViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_content
     *
     * @return the value of article.article_content
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_content
     *
     * @param articleContent the value for article.article_content
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_content_md
     *
     * @return the value of article.article_content_md
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getArticleContentMd() {
        return articleContentMd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_content_md
     *
     * @param articleContentMd the value for article.article_content_md
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleContentMd(String articleContentMd) {
        this.articleContentMd = articleContentMd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", articleNewstime=").append(articleNewstime);
        sb.append(", articleStatus=").append(articleStatus);
        sb.append(", articleSummary=").append(articleSummary);
        sb.append(", articleThumbnail=").append(articleThumbnail);
        sb.append(", articleTitle=").append(articleTitle);
        sb.append(", articleType=").append(articleType);
        sb.append(", articlePost=").append(articlePost);
        sb.append(", articleCommentStatus=").append(articleCommentStatus);
        sb.append(", articleLasttime=").append(articleLasttime);
        sb.append(", articleUrl=").append(articleUrl);
        sb.append(", articleViews=").append(articleViews);
        sb.append(", articleContent=").append(articleContent);
        sb.append(", articleContentMd=").append(articleContentMd);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}