package com.fnbory.myblog.entities;

import java.io.Serializable;

public class ArticleTag implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag.article_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag.tag_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Long tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_tag
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag.article_id
     *
     * @return the value of article_tag.article_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag.article_id
     *
     * @param articleId the value for article_tag.article_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag.tag_id
     *
     * @return the value of article_tag.tag_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag.tag_id
     *
     * @param tagId the value for article_tag.tag_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", tagId=").append(tagId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}