package com.fnbory.myblog.entities;

import java.io.Serializable;

public class ArticleCategoryRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category_relation.article_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category_relation.category_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_category_relation
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category_relation.article_id
     *
     * @return the value of article_category_relation.article_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category_relation.article_id
     *
     * @param articleId the value for article_category_relation.article_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category_relation.category_id
     *
     * @return the value of article_category_relation.category_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category_relation.category_id
     *
     * @param categoryId the value for article_category_relation.category_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_relation
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}