package com.fnbory.myblog.entities;

import java.io.Serializable;

public class Attachment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.picture_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String pictureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.picture_path
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String picturePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.picture_thumbnail
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String pictureThumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.picture_type
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String pictureType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.picture_create_date
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String pictureCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.picture_size
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String pictureSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.picture_suffix
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String pictureSuffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.picture_wh
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String pictureWh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attachment
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.id
     *
     * @return the value of attachment.id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.id
     *
     * @param id the value for attachment.id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.picture_name
     *
     * @return the value of attachment.picture_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getPictureName() {
        return pictureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.picture_name
     *
     * @param pictureName the value for attachment.picture_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setPictureName(String pictureName) {
        this.pictureName = pictureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.picture_path
     *
     * @return the value of attachment.picture_path
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.picture_path
     *
     * @param picturePath the value for attachment.picture_path
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.picture_thumbnail
     *
     * @return the value of attachment.picture_thumbnail
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getPictureThumbnail() {
        return pictureThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.picture_thumbnail
     *
     * @param pictureThumbnail the value for attachment.picture_thumbnail
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setPictureThumbnail(String pictureThumbnail) {
        this.pictureThumbnail = pictureThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.picture_type
     *
     * @return the value of attachment.picture_type
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getPictureType() {
        return pictureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.picture_type
     *
     * @param pictureType the value for attachment.picture_type
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setPictureType(String pictureType) {
        this.pictureType = pictureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.picture_create_date
     *
     * @return the value of attachment.picture_create_date
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getPictureCreateDate() {
        return pictureCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.picture_create_date
     *
     * @param pictureCreateDate the value for attachment.picture_create_date
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setPictureCreateDate(String pictureCreateDate) {
        this.pictureCreateDate = pictureCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.picture_size
     *
     * @return the value of attachment.picture_size
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getPictureSize() {
        return pictureSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.picture_size
     *
     * @param pictureSize the value for attachment.picture_size
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setPictureSize(String pictureSize) {
        this.pictureSize = pictureSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.picture_suffix
     *
     * @return the value of attachment.picture_suffix
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getPictureSuffix() {
        return pictureSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.picture_suffix
     *
     * @param pictureSuffix the value for attachment.picture_suffix
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setPictureSuffix(String pictureSuffix) {
        this.pictureSuffix = pictureSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.picture_wh
     *
     * @return the value of attachment.picture_wh
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getPictureWh() {
        return pictureWh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.picture_wh
     *
     * @param pictureWh the value for attachment.picture_wh
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setPictureWh(String pictureWh) {
        this.pictureWh = pictureWh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pictureName=").append(pictureName);
        sb.append(", picturePath=").append(picturePath);
        sb.append(", pictureThumbnail=").append(pictureThumbnail);
        sb.append(", pictureType=").append(pictureType);
        sb.append(", pictureCreateDate=").append(pictureCreateDate);
        sb.append(", pictureSize=").append(pictureSize);
        sb.append(", pictureSuffix=").append(pictureSuffix);
        sb.append(", pictureWh=").append(pictureWh);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}