package com.fnbory.myblog.entities;

import java.io.Serializable;

public class Category implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String categoryUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_describe
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String categoryDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_id
     *
     * @return the value of category.category_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_id
     *
     * @param categoryId the value for category.category_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_url
     *
     * @return the value of category.category_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getCategoryUrl() {
        return categoryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_url
     *
     * @param categoryUrl the value for category.category_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setCategoryUrl(String categoryUrl) {
        this.categoryUrl = categoryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_describe
     *
     * @return the value of category.category_describe
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getCategoryDescribe() {
        return categoryDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_describe
     *
     * @param categoryDescribe the value for category.category_describe
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setCategoryDescribe(String categoryDescribe) {
        this.categoryDescribe = categoryDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", categoryId=").append(categoryId);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", categoryUrl=").append(categoryUrl);
        sb.append(", categoryDescribe=").append(categoryDescribe);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}