package com.fnbory.myblog.entities;

import java.io.Serializable;

public class Link implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_logo
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String linkLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_describe
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String linkDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table link
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_id
     *
     * @return the value of link.link_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_id
     *
     * @param linkId the value for link.link_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_name
     *
     * @return the value of link.link_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_name
     *
     * @param linkName the value for link.link_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_url
     *
     * @return the value of link.link_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_url
     *
     * @param linkUrl the value for link.link_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_logo
     *
     * @return the value of link.link_logo
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getLinkLogo() {
        return linkLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_logo
     *
     * @param linkLogo the value for link.link_logo
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLinkLogo(String linkLogo) {
        this.linkLogo = linkLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_describe
     *
     * @return the value of link.link_describe
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getLinkDescribe() {
        return linkDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_describe
     *
     * @param linkDescribe the value for link.link_describe
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLinkDescribe(String linkDescribe) {
        this.linkDescribe = linkDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", linkId=").append(linkId);
        sb.append(", linkName=").append(linkName);
        sb.append(", linkUrl=").append(linkUrl);
        sb.append(", linkLogo=").append(linkLogo);
        sb.append(", linkDescribe=").append(linkDescribe);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}