package com.fnbory.myblog.entities;

import java.io.Serializable;
import java.util.Date;

public class Logs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_title
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String logTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_content
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String logContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_ip
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String logIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_date
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Date logDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logs
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_id
     *
     * @return the value of logs.log_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_id
     *
     * @param logId the value for logs.log_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_title
     *
     * @return the value of logs.log_title
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getLogTitle() {
        return logTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_title
     *
     * @param logTitle the value for logs.log_title
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLogTitle(String logTitle) {
        this.logTitle = logTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_content
     *
     * @return the value of logs.log_content
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getLogContent() {
        return logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_content
     *
     * @param logContent the value for logs.log_content
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLogContent(String logContent) {
        this.logContent = logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_ip
     *
     * @return the value of logs.log_ip
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getLogIp() {
        return logIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_ip
     *
     * @param logIp the value for logs.log_ip
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLogIp(String logIp) {
        this.logIp = logIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_date
     *
     * @return the value of logs.log_date
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_date
     *
     * @param logDate the value for logs.log_date
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logId=").append(logId);
        sb.append(", logTitle=").append(logTitle);
        sb.append(", logContent=").append(logContent);
        sb.append(", logIp=").append(logIp);
        sb.append(", logDate=").append(logDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}