package com.fnbory.myblog.entities;

import java.io.Serializable;

public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_icon
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String menuIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_sort
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer menuSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_target
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String menuTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_id
     *
     * @return the value of menu.menu_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_id
     *
     * @param menuId the value for menu.menu_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_icon
     *
     * @return the value of menu.menu_icon
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_icon
     *
     * @param menuIcon the value for menu.menu_icon
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_name
     *
     * @return the value of menu.menu_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_name
     *
     * @param menuName the value for menu.menu_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_sort
     *
     * @return the value of menu.menu_sort
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getMenuSort() {
        return menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_sort
     *
     * @param menuSort the value for menu.menu_sort
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setMenuSort(Integer menuSort) {
        this.menuSort = menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_target
     *
     * @return the value of menu.menu_target
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getMenuTarget() {
        return menuTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_target
     *
     * @param menuTarget the value for menu.menu_target
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setMenuTarget(String menuTarget) {
        this.menuTarget = menuTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_url
     *
     * @return the value of menu.menu_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_url
     *
     * @param menuUrl the value for menu.menu_url
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuId=").append(menuId);
        sb.append(", menuIcon=").append(menuIcon);
        sb.append(", menuName=").append(menuName);
        sb.append(", menuSort=").append(menuSort);
        sb.append(", menuTarget=").append(menuTarget);
        sb.append(", menuUrl=").append(menuUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}