package com.fnbory.myblog.entities;

import java.io.Serializable;
import java.util.Date;

public class Theme implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.theme_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String themeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.theme_describe
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String themeDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.theme_thumbnail
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private String themeThumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.theme_status
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Integer themeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.theme_create_time
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private Date themeCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.id
     *
     * @return the value of theme.id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.id
     *
     * @param id the value for theme.id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.theme_name
     *
     * @return the value of theme.theme_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getThemeName() {
        return themeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.theme_name
     *
     * @param themeName the value for theme.theme_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setThemeName(String themeName) {
        this.themeName = themeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.theme_describe
     *
     * @return the value of theme.theme_describe
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getThemeDescribe() {
        return themeDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.theme_describe
     *
     * @param themeDescribe the value for theme.theme_describe
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setThemeDescribe(String themeDescribe) {
        this.themeDescribe = themeDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.theme_thumbnail
     *
     * @return the value of theme.theme_thumbnail
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getThemeThumbnail() {
        return themeThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.theme_thumbnail
     *
     * @param themeThumbnail the value for theme.theme_thumbnail
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setThemeThumbnail(String themeThumbnail) {
        this.themeThumbnail = themeThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.theme_status
     *
     * @return the value of theme.theme_status
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getThemeStatus() {
        return themeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.theme_status
     *
     * @param themeStatus the value for theme.theme_status
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setThemeStatus(Integer themeStatus) {
        this.themeStatus = themeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.theme_create_time
     *
     * @return the value of theme.theme_create_time
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Date getThemeCreateTime() {
        return themeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.theme_create_time
     *
     * @param themeCreateTime the value for theme.theme_create_time
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setThemeCreateTime(Date themeCreateTime) {
        this.themeCreateTime = themeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", themeName=").append(themeName);
        sb.append(", themeDescribe=").append(themeDescribe);
        sb.append(", themeThumbnail=").append(themeThumbnail);
        sb.append(", themeStatus=").append(themeStatus);
        sb.append(", themeCreateTime=").append(themeCreateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}