package com.fnbory.myblog.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ThemeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public ThemeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andThemeNameIsNull() {
            addCriterion("theme_name is null");
            return (Criteria) this;
        }

        public Criteria andThemeNameIsNotNull() {
            addCriterion("theme_name is not null");
            return (Criteria) this;
        }

        public Criteria andThemeNameEqualTo(String value) {
            addCriterion("theme_name =", value, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeNameNotEqualTo(String value) {
            addCriterion("theme_name <>", value, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeNameGreaterThan(String value) {
            addCriterion("theme_name >", value, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeNameGreaterThanOrEqualTo(String value) {
            addCriterion("theme_name >=", value, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeNameLessThan(String value) {
            addCriterion("theme_name <", value, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeNameLessThanOrEqualTo(String value) {
            addCriterion("theme_name <=", value, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeNameLike(String value) {
            addCriterion("theme_name like", value, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeNameNotLike(String value) {
            addCriterion("theme_name not like", value, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeNameIn(List<String> values) {
            addCriterion("theme_name in", values, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeNameNotIn(List<String> values) {
            addCriterion("theme_name not in", values, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeNameBetween(String value1, String value2) {
            addCriterion("theme_name between", value1, value2, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeNameNotBetween(String value1, String value2) {
            addCriterion("theme_name not between", value1, value2, "themeName");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeIsNull() {
            addCriterion("theme_describe is null");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeIsNotNull() {
            addCriterion("theme_describe is not null");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeEqualTo(String value) {
            addCriterion("theme_describe =", value, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeNotEqualTo(String value) {
            addCriterion("theme_describe <>", value, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeGreaterThan(String value) {
            addCriterion("theme_describe >", value, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeGreaterThanOrEqualTo(String value) {
            addCriterion("theme_describe >=", value, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeLessThan(String value) {
            addCriterion("theme_describe <", value, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeLessThanOrEqualTo(String value) {
            addCriterion("theme_describe <=", value, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeLike(String value) {
            addCriterion("theme_describe like", value, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeNotLike(String value) {
            addCriterion("theme_describe not like", value, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeIn(List<String> values) {
            addCriterion("theme_describe in", values, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeNotIn(List<String> values) {
            addCriterion("theme_describe not in", values, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeBetween(String value1, String value2) {
            addCriterion("theme_describe between", value1, value2, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeDescribeNotBetween(String value1, String value2) {
            addCriterion("theme_describe not between", value1, value2, "themeDescribe");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailIsNull() {
            addCriterion("theme_thumbnail is null");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailIsNotNull() {
            addCriterion("theme_thumbnail is not null");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailEqualTo(String value) {
            addCriterion("theme_thumbnail =", value, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailNotEqualTo(String value) {
            addCriterion("theme_thumbnail <>", value, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailGreaterThan(String value) {
            addCriterion("theme_thumbnail >", value, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailGreaterThanOrEqualTo(String value) {
            addCriterion("theme_thumbnail >=", value, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailLessThan(String value) {
            addCriterion("theme_thumbnail <", value, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailLessThanOrEqualTo(String value) {
            addCriterion("theme_thumbnail <=", value, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailLike(String value) {
            addCriterion("theme_thumbnail like", value, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailNotLike(String value) {
            addCriterion("theme_thumbnail not like", value, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailIn(List<String> values) {
            addCriterion("theme_thumbnail in", values, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailNotIn(List<String> values) {
            addCriterion("theme_thumbnail not in", values, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailBetween(String value1, String value2) {
            addCriterion("theme_thumbnail between", value1, value2, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeThumbnailNotBetween(String value1, String value2) {
            addCriterion("theme_thumbnail not between", value1, value2, "themeThumbnail");
            return (Criteria) this;
        }

        public Criteria andThemeStatusIsNull() {
            addCriterion("theme_status is null");
            return (Criteria) this;
        }

        public Criteria andThemeStatusIsNotNull() {
            addCriterion("theme_status is not null");
            return (Criteria) this;
        }

        public Criteria andThemeStatusEqualTo(Integer value) {
            addCriterion("theme_status =", value, "themeStatus");
            return (Criteria) this;
        }

        public Criteria andThemeStatusNotEqualTo(Integer value) {
            addCriterion("theme_status <>", value, "themeStatus");
            return (Criteria) this;
        }

        public Criteria andThemeStatusGreaterThan(Integer value) {
            addCriterion("theme_status >", value, "themeStatus");
            return (Criteria) this;
        }

        public Criteria andThemeStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("theme_status >=", value, "themeStatus");
            return (Criteria) this;
        }

        public Criteria andThemeStatusLessThan(Integer value) {
            addCriterion("theme_status <", value, "themeStatus");
            return (Criteria) this;
        }

        public Criteria andThemeStatusLessThanOrEqualTo(Integer value) {
            addCriterion("theme_status <=", value, "themeStatus");
            return (Criteria) this;
        }

        public Criteria andThemeStatusIn(List<Integer> values) {
            addCriterion("theme_status in", values, "themeStatus");
            return (Criteria) this;
        }

        public Criteria andThemeStatusNotIn(List<Integer> values) {
            addCriterion("theme_status not in", values, "themeStatus");
            return (Criteria) this;
        }

        public Criteria andThemeStatusBetween(Integer value1, Integer value2) {
            addCriterion("theme_status between", value1, value2, "themeStatus");
            return (Criteria) this;
        }

        public Criteria andThemeStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("theme_status not between", value1, value2, "themeStatus");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeIsNull() {
            addCriterion("theme_create_time is null");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeIsNotNull() {
            addCriterion("theme_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeEqualTo(Date value) {
            addCriterion("theme_create_time =", value, "themeCreateTime");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeNotEqualTo(Date value) {
            addCriterion("theme_create_time <>", value, "themeCreateTime");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeGreaterThan(Date value) {
            addCriterion("theme_create_time >", value, "themeCreateTime");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("theme_create_time >=", value, "themeCreateTime");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeLessThan(Date value) {
            addCriterion("theme_create_time <", value, "themeCreateTime");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("theme_create_time <=", value, "themeCreateTime");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeIn(List<Date> values) {
            addCriterion("theme_create_time in", values, "themeCreateTime");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeNotIn(List<Date> values) {
            addCriterion("theme_create_time not in", values, "themeCreateTime");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeBetween(Date value1, Date value2) {
            addCriterion("theme_create_time between", value1, value2, "themeCreateTime");
            return (Criteria) this;
        }

        public Criteria andThemeCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("theme_create_time not between", value1, value2, "themeCreateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theme
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 05 13:12:14 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theme
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}