package com.fnbory.myblog.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andLoginBanIsNull() {
            addCriterion("login_ban is null");
            return (Criteria) this;
        }

        public Criteria andLoginBanIsNotNull() {
            addCriterion("login_ban is not null");
            return (Criteria) this;
        }

        public Criteria andLoginBanEqualTo(String value) {
            addCriterion("login_ban =", value, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginBanNotEqualTo(String value) {
            addCriterion("login_ban <>", value, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginBanGreaterThan(String value) {
            addCriterion("login_ban >", value, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginBanGreaterThanOrEqualTo(String value) {
            addCriterion("login_ban >=", value, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginBanLessThan(String value) {
            addCriterion("login_ban <", value, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginBanLessThanOrEqualTo(String value) {
            addCriterion("login_ban <=", value, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginBanLike(String value) {
            addCriterion("login_ban like", value, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginBanNotLike(String value) {
            addCriterion("login_ban not like", value, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginBanIn(List<String> values) {
            addCriterion("login_ban in", values, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginBanNotIn(List<String> values) {
            addCriterion("login_ban not in", values, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginBanBetween(String value1, String value2) {
            addCriterion("login_ban between", value1, value2, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginBanNotBetween(String value1, String value2) {
            addCriterion("login_ban not between", value1, value2, "loginBan");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesIsNull() {
            addCriterion("login_false_times is null");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesIsNotNull() {
            addCriterion("login_false_times is not null");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesEqualTo(Integer value) {
            addCriterion("login_false_times =", value, "loginFalseTimes");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesNotEqualTo(Integer value) {
            addCriterion("login_false_times <>", value, "loginFalseTimes");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesGreaterThan(Integer value) {
            addCriterion("login_false_times >", value, "loginFalseTimes");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_false_times >=", value, "loginFalseTimes");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesLessThan(Integer value) {
            addCriterion("login_false_times <", value, "loginFalseTimes");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesLessThanOrEqualTo(Integer value) {
            addCriterion("login_false_times <=", value, "loginFalseTimes");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesIn(List<Integer> values) {
            addCriterion("login_false_times in", values, "loginFalseTimes");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesNotIn(List<Integer> values) {
            addCriterion("login_false_times not in", values, "loginFalseTimes");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesBetween(Integer value1, Integer value2) {
            addCriterion("login_false_times between", value1, value2, "loginFalseTimes");
            return (Criteria) this;
        }

        public Criteria andLoginFalseTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("login_false_times not between", value1, value2, "loginFalseTimes");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeIsNull() {
            addCriterion("login_last_time is null");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeIsNotNull() {
            addCriterion("login_last_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeEqualTo(Date value) {
            addCriterion("login_last_time =", value, "loginLastTime");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeNotEqualTo(Date value) {
            addCriterion("login_last_time <>", value, "loginLastTime");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeGreaterThan(Date value) {
            addCriterion("login_last_time >", value, "loginLastTime");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("login_last_time >=", value, "loginLastTime");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeLessThan(Date value) {
            addCriterion("login_last_time <", value, "loginLastTime");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeLessThanOrEqualTo(Date value) {
            addCriterion("login_last_time <=", value, "loginLastTime");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeIn(List<Date> values) {
            addCriterion("login_last_time in", values, "loginLastTime");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeNotIn(List<Date> values) {
            addCriterion("login_last_time not in", values, "loginLastTime");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeBetween(Date value1, Date value2) {
            addCriterion("login_last_time between", value1, value2, "loginLastTime");
            return (Criteria) this;
        }

        public Criteria andLoginLastTimeNotBetween(Date value1, Date value2) {
            addCriterion("login_last_time not between", value1, value2, "loginLastTime");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgIsNull() {
            addCriterion("user_headimg is null");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgIsNotNull() {
            addCriterion("user_headimg is not null");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgEqualTo(String value) {
            addCriterion("user_headimg =", value, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgNotEqualTo(String value) {
            addCriterion("user_headimg <>", value, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgGreaterThan(String value) {
            addCriterion("user_headimg >", value, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgGreaterThanOrEqualTo(String value) {
            addCriterion("user_headimg >=", value, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgLessThan(String value) {
            addCriterion("user_headimg <", value, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgLessThanOrEqualTo(String value) {
            addCriterion("user_headimg <=", value, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgLike(String value) {
            addCriterion("user_headimg like", value, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgNotLike(String value) {
            addCriterion("user_headimg not like", value, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgIn(List<String> values) {
            addCriterion("user_headimg in", values, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgNotIn(List<String> values) {
            addCriterion("user_headimg not in", values, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgBetween(String value1, String value2) {
            addCriterion("user_headimg between", value1, value2, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserHeadimgNotBetween(String value1, String value2) {
            addCriterion("user_headimg not between", value1, value2, "userHeadimg");
            return (Criteria) this;
        }

        public Criteria andUserExplainIsNull() {
            addCriterion("user_explain is null");
            return (Criteria) this;
        }

        public Criteria andUserExplainIsNotNull() {
            addCriterion("user_explain is not null");
            return (Criteria) this;
        }

        public Criteria andUserExplainEqualTo(String value) {
            addCriterion("user_explain =", value, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserExplainNotEqualTo(String value) {
            addCriterion("user_explain <>", value, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserExplainGreaterThan(String value) {
            addCriterion("user_explain >", value, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserExplainGreaterThanOrEqualTo(String value) {
            addCriterion("user_explain >=", value, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserExplainLessThan(String value) {
            addCriterion("user_explain <", value, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserExplainLessThanOrEqualTo(String value) {
            addCriterion("user_explain <=", value, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserExplainLike(String value) {
            addCriterion("user_explain like", value, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserExplainNotLike(String value) {
            addCriterion("user_explain not like", value, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserExplainIn(List<String> values) {
            addCriterion("user_explain in", values, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserExplainNotIn(List<String> values) {
            addCriterion("user_explain not in", values, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserExplainBetween(String value1, String value2) {
            addCriterion("user_explain between", value1, value2, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserExplainNotBetween(String value1, String value2) {
            addCriterion("user_explain not between", value1, value2, "userExplain");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameIsNull() {
            addCriterion("user_display_name is null");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameIsNotNull() {
            addCriterion("user_display_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameEqualTo(String value) {
            addCriterion("user_display_name =", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameNotEqualTo(String value) {
            addCriterion("user_display_name <>", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameGreaterThan(String value) {
            addCriterion("user_display_name >", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_display_name >=", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameLessThan(String value) {
            addCriterion("user_display_name <", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameLessThanOrEqualTo(String value) {
            addCriterion("user_display_name <=", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameLike(String value) {
            addCriterion("user_display_name like", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameNotLike(String value) {
            addCriterion("user_display_name not like", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameIn(List<String> values) {
            addCriterion("user_display_name in", values, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameNotIn(List<String> values) {
            addCriterion("user_display_name not in", values, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameBetween(String value1, String value2) {
            addCriterion("user_display_name between", value1, value2, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameNotBetween(String value1, String value2) {
            addCriterion("user_display_name not between", value1, value2, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNull() {
            addCriterion("user_email is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNotNull() {
            addCriterion("user_email is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailEqualTo(String value) {
            addCriterion("user_email =", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotEqualTo(String value) {
            addCriterion("user_email <>", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThan(String value) {
            addCriterion("user_email >", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
            addCriterion("user_email >=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThan(String value) {
            addCriterion("user_email <", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThanOrEqualTo(String value) {
            addCriterion("user_email <=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLike(String value) {
            addCriterion("user_email like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotLike(String value) {
            addCriterion("user_email not like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailIn(List<String> values) {
            addCriterion("user_email in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotIn(List<String> values) {
            addCriterion("user_email not in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailBetween(String value1, String value2) {
            addCriterion("user_email between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotBetween(String value1, String value2) {
            addCriterion("user_email not between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("user_password is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("user_password is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("user_password =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("user_password <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("user_password >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("user_password >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("user_password <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("user_password <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("user_password like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("user_password not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("user_password in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("user_password not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("user_password between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("user_password not between", value1, value2, "userPassword");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 05 13:12:14 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}