package com.fnbory.myblog.entities;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {

    private Integer userId;

    private String loginBan;

    private Integer loginFalseTimes;

    private Date loginLastTime;

    private String userHeadimg;

    private String userExplain;

    private String userDisplayName;

    private String userEmail;

    private String userName;

    private String userPassword;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_ban
     *
     * @return the value of user.login_ban
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getLoginBan() {
        return loginBan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_ban
     *
     * @param loginBan the value for user.login_ban
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLoginBan(String loginBan) {
        this.loginBan = loginBan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_false_times
     *
     * @return the value of user.login_false_times
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Integer getLoginFalseTimes() {
        return loginFalseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_false_times
     *
     * @param loginFalseTimes the value for user.login_false_times
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLoginFalseTimes(Integer loginFalseTimes) {
        this.loginFalseTimes = loginFalseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_last_time
     *
     * @return the value of user.login_last_time
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public Date getLoginLastTime() {
        return loginLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_last_time
     *
     * @param loginLastTime the value for user.login_last_time
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setLoginLastTime(Date loginLastTime) {
        this.loginLastTime = loginLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_headimg
     *
     * @return the value of user.user_headimg
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getUserHeadimg() {
        return userHeadimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_headimg
     *
     * @param userHeadimg the value for user.user_headimg
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setUserHeadimg(String userHeadimg) {
        this.userHeadimg = userHeadimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_explain
     *
     * @return the value of user.user_explain
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getUserExplain() {
        return userExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_explain
     *
     * @param userExplain the value for user.user_explain
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setUserExplain(String userExplain) {
        this.userExplain = userExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_display_name
     *
     * @return the value of user.user_display_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getUserDisplayName() {
        return userDisplayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_display_name
     *
     * @param userDisplayName the value for user.user_display_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setUserDisplayName(String userDisplayName) {
        this.userDisplayName = userDisplayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_email
     *
     * @return the value of user.user_email
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_email
     *
     * @param userEmail the value for user.user_email
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", loginBan=").append(loginBan);
        sb.append(", loginFalseTimes=").append(loginFalseTimes);
        sb.append(", loginLastTime=").append(loginLastTime);
        sb.append(", userHeadimg=").append(userHeadimg);
        sb.append(", userExplain=").append(userExplain);
        sb.append(", userDisplayName=").append(userDisplayName);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", userName=").append(userName);
        sb.append(", userPassword=").append(userPassword);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}