package com.fnbory.myblog.dao;

import com.fnbory.myblog.entities.ArticleCategoryRelation;
import com.fnbory.myblog.entities.ArticleCategoryRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCategoryRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_relation
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int countByExample(ArticleCategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_relation
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int deleteByExample(ArticleCategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_relation
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int insert(ArticleCategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_relation
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int insertSelective(ArticleCategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_relation
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    List<ArticleCategoryRelation> selectByExample(ArticleCategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_relation
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") ArticleCategoryRelation record, @Param("example") ArticleCategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_relation
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int updateByExample(@Param("record") ArticleCategoryRelation record, @Param("example") ArticleCategoryRelationExample example);
}