package com.fnbory.myblog.dao;

import com.fnbory.myblog.entities.ArticleTag;
import com.fnbory.myblog.entities.ArticleTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int countByExample(ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int deleteByExample(ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int insert(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int insertSelective(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    List<ArticleTag> selectByExample(ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") ArticleTag record, @Param("example") ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int updateByExample(@Param("record") ArticleTag record, @Param("example") ArticleTagExample example);
}