package com.fnbory.myblog.dao;

import com.fnbory.myblog.entities.Options;
import com.fnbory.myblog.entities.OptionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int countByExample(OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int deleteByExample(OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int deleteByPrimaryKey(String optionName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int insert(Options record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int insertSelective(Options record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    List<Options> selectByExampleWithBLOBs(OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    List<Options> selectByExample(OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    Options selectByPrimaryKey(String optionName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") Options record, @Param("example") OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Options record, @Param("example") OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int updateByExample(@Param("record") Options record, @Param("example") OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int updateByPrimaryKeySelective(Options record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Wed Jun 05 13:12:14 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Options record);
}